BlueBrain/mod2c

share/nrnunits.lib

Corresponding commit in nrnhines/nrn is
https://github.com/nrnhines/nrn/commit/e0950a19a722b661882d1609fe7748ec67b68ba8

Sync with changes from NEURON for nrnunits.lib

---

src/mod2c_core/deriv.c
src/mod2c_core/solve.c

Similar to derivimplicit, included _kinderiv.h.
@nrnhines : call to `add_deriv_imp_really` seems to be safe as we use that only to decide if `static or non-static` declaration of state functions.

Add support for thread safe euler method (similar to NEURON)

---

src/mod2c_core/noccout.c
src/mod2c_core/nocpout.c
test/validation/mod2c_core/c/NaSm.c
test/validation/mod2c_core/c/Nap.c
test/validation/mod2c_core/c/NapDA.c
test/validation/mod2c_core/c/NapIn.c
test/validation/mod2c_core/c/Nap_E.c
test/validation/mod2c_core/c/Nap_No.c
test/validation/mod2c_core/c/SynNMDA10_1.c
test/validation/mod2c_core/c/SynNMDA10_2.c
test/validation/mod2c_core/c/SynNMDA10_2_2.c
test/validation/mod2c_core/c/SynNMDA16.c
test/validation/mod2c_core/c/SynNMDA16_2.c
test/validation/mod2c_core/c/is.c
test/validation/mod2c_core/c/zoidsyn.c

Random123 header need to be included first for proper
assembly target selection. This commits reorder the
included headers.

Fix random123 compiling error with latest clang 9 on OSX

---

src/mod2c_core/deriv.c
src/mod2c_core/kinetic.c
src/mod2c_core/nocpout.c
src/mod2c_core/parsact.c
src/mod2c_core/simultan.c
src/mod2c_core/solve.c
test/validation/mod2c_core/c/NaSm.c
test/validation/mod2c_core/c/Nap.c
test/validation/mod2c_core/c/NapDA.c
test/validation/mod2c_core/c/NapIn.c
test/validation/mod2c_core/c/Nap_E.c
test/validation/mod2c_core/c/Nap_No.c
test/validation/mod2c_core/c/SynNMDA10_1.c
test/validation/mod2c_core/c/SynNMDA10_2.c
test/validation/mod2c_core/c/SynNMDA10_2_2.c
test/validation/mod2c_core/c/SynNMDA16.c
test/validation/mod2c_core/c/SynNMDA16_2.c
test/validation/mod2c_core/c/is.c
test/validation/mod2c_core/c/zoidsyn.c

A lot of extern declarations that potentially conflict with what is delcared in coreneuron. We remove them and add the fitting coreneuron headers instead. 
Using this way, declarations are all centralized in one place.

remove all non necessary extern declarations

---

src/mod2c_core/nocpout.c
test/validation/mod2c_core/c/NaSm.c
test/validation/mod2c_core/c/Nap.c
test/validation/mod2c_core/c/NapDA.c
test/validation/mod2c_core/c/NapIn.c
test/validation/mod2c_core/c/Nap_E.c
test/validation/mod2c_core/c/Nap_No.c
test/validation/mod2c_core/c/SynNMDA10_1.c
test/validation/mod2c_core/c/SynNMDA10_2.c
test/validation/mod2c_core/c/SynNMDA10_2_2.c
test/validation/mod2c_core/c/SynNMDA16.c
test/validation/mod2c_core/c/SynNMDA16_2.c
test/validation/mod2c_core/c/is.c
test/validation/mod2c_core/c/zoidsyn.c

has macro definitions without "_" i.e. without use of md1redef.h. When this
headers get included, it results into macro redefinition warning.
Undef all relevant macros in mod2c.

Avoid macro redefinition warnings: coreneuron's mech/mod2c_core_thread.h

---

src/mod2c_core/noccout.c
src/mod2c_core/nocpout.c
test/validation/mod2c_core/cpp/NaSm.cpp
test/validation/mod2c_core/cpp/Nap.cpp
test/validation/mod2c_core/cpp/NapDA.cpp
test/validation/mod2c_core/cpp/NapIn.cpp
test/validation/mod2c_core/cpp/Nap_E.cpp
test/validation/mod2c_core/cpp/Nap_No.cpp
test/validation/mod2c_core/cpp/SynNMDA10_1.cpp
test/validation/mod2c_core/cpp/SynNMDA10_2.cpp
test/validation/mod2c_core/cpp/SynNMDA10_2_2.cpp
test/validation/mod2c_core/cpp/SynNMDA16.cpp
test/validation/mod2c_core/cpp/SynNMDA16_2.cpp
test/validation/mod2c_core/cpp/is.cpp
test/validation/mod2c_core/cpp/zoidsyn.cpp

Hi Michael,
I spent some time digging into different PGI compiler versions and why C++ code from mod2c wasn't working for GPU. Here is summary : 
* When there are large functions, especially nested ones, nrn_state()->state()->rates()->trates().....and son : pgc++ doesn't inline all functions. Same call chain gets inlined if its .c file (i.e. pgcc). We have pragma annotation for `nrn_state` only. As inlining is failed, pgc++ gives error while generating gpu code. Solution for this is : 
```
#pragma acc routine seq
int state() {
}
#pragma routine seq
int rates() {
}
double nrn_state() {
#pragma acc parallel for
for () {
.........
}
}
```
With this, when inlining is failed, device kernel is generated for `state` and other functions. This way, gpu code can work fine. So, now all …

Fix PGI and OpenACC issues with latest CoreNEURON master with C++

---

src/mod2c_core/nocpout.c
test/validation/mod2c_core/cpp/NaSm.cpp
test/validation/mod2c_core/cpp/NapDA.cpp
test/validation/mod2c_core/cpp/Nap_E.cpp
test/validation/mod2c_core/cpp/Nap_No.cpp
test/validation/mod2c_core/cpp/SynNMDA10_2_2.cpp
test/validation/mod2c_core/cpp/SynNMDA16.cpp
test/validation/mod2c_core/cpp/SynNMDA16_2.cpp
test/validation/mod2c_core/cpp/is.cpp
test/validation/mod2c_core/cpp/zoidsyn.cpp

- On OS X Intel compiler also defines `__clang__` macro
- If clang pragma is used instead of Intel's `#pragma ivdep`
then loop is not vectorized.
- To avoid this, intel, pgi, cray pragma's are inserted before clang & gcc

Bug fix for intel ivdep pragma order

---

src/mod2c_core/nocpout.c
test/validation/mod2c_core/cpp/SynNMDA10_2_2.cpp
test/validation/mod2c_core/cpp/SynNMDA16_2.cpp
test/validation/mod2c_core/cpp/zoidsyn.cpp

This only works on CPU, so we throw an error (via assert) for OpenACC.
Updated tests accordingly

NetSendBuffer_t can now be dynamically grown

---

CMakeLists.txt

Update minimum version of cmake to 3.7 as Coreneuron (the only builder of mod2c).

Use version of project command

---

src/mod2c_core/CMakeLists.txt

- mod2c_core binary is often used on the login/front-end/build node
which could be different than compute node cpu type.
- if we build with O2,O3 or compiler flags of CoreNEURON then this
could generate binary that doesnt run on front-end node.
- to avoid this, use debug flags to build mod2c binary as performance
is not a concern with this specific binary

Build mod2c_core with dbeug flags

---

src/mod2c_core/nocpout.c
test/validation/mod2c_core/cpp/NaSm.cpp
test/validation/mod2c_core/cpp/NapDA.cpp
test/validation/mod2c_core/cpp/Nap_E.cpp
test/validation/mod2c_core/cpp/Nap_No.cpp
test/validation/mod2c_core/cpp/SynNMDA10_2_2.cpp
test/validation/mod2c_core/cpp/SynNMDA16.cpp
test/validation/mod2c_core/cpp/SynNMDA16_2.cpp
test/validation/mod2c_core/cpp/is.cpp
test/validation/mod2c_core/cpp/zoidsyn.cpp

* when array pointer is passed, we need to specify array
bounds
* we now use new ion_global_map_member_size variable in
coreneuron which is defined with value 3
* no need to have PG_ACC_BUGS as this was not a bug

Remove usage of PG_ACC_BUGS

---

src/mod2c_core/noccout.c
test/validation/mod/Nap.mod
test/validation/mod/NapIn.mod
test/validation/mod/SynNMDA10_1.mod
test/validation/mod/SynNMDA10_2.mod
test/validation/mod2c_core/cpp/Nap.cpp
test/validation/mod2c_core/cpp/NapIn.cpp
test/validation/mod2c_core/cpp/SynNMDA10_1.cpp
test/validation/mod2c_core/cpp/SynNMDA10_2.cpp

- When mod file is not thread safe, we emit non-compilable
code or a code than can be wrong when vectorisation is enabled.
This results into confusing behaviour for end users.
- Instead, it's safe and CPU/GPU compatible if user make the model
theadsfae explicitly.
- Update the test mod files accordingly.
Note : cpp files generated are not commited in this commit to avoid
the clutter. I will do that in next commit.

Abort when mod file is not thread safe

---

src/mod2c_core/lex.l

* new clang version gives following error:
```
lex.c:1611:40: error: implicit declaration of function 'isatty' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
```

Avoid error with new clang/flex : implicit declaration of function 'isatty'

---

src/mod2c_core/noccout.c

Previously this code was not emitted when OpenACC was enabled.

Support fast_imem on GPU

---

src/mod2c_core/nocpout.c

Related to the psolve-direct PR for neuronsimulator/nrn#1192 .
Needed for successful test in that PR for test/coreneuron/mod/watchrange.mod

Only one WATCH statement can be triggered at a time

---

src/mod2c_core/nocpout.c
test/validation/mod2c_core/cpp/SynNMDA10_2_2.cpp
test/validation/mod2c_core/cpp/SynNMDA16_2.cpp
test/validation/mod2c_core/cpp/zoidsyn.cpp

* During psolve-direct PR in coreneuron (#528), we saw that following
code produces random errors:
#pragma acc atomic capture
_i = _nsb->_cnt++;
if (_i >= _nsb->_size) {
int NetSendBuffer_t_not_large_enough = 0;
assert(NetSendBuffer_t_not_large_enough);
}
In the presence of assert(), _i value is duplicated. This error is
not easily reproducible in standalone example and also happens
randomly during the execution. The code works fine if we use -O0
optimization.
* It's not clear if this is a compiler bug. For now, avoid use assert()
in the atomic capture.
* Error handling will be done in CoreNEURON by checking the `nsb->count`
in the `update_net_send_buffer_on_host()` implementation.
* Update the test code

Avoid use of assert in OpenACC kernel along with use atomic capture

---

src/mod2c_core/noccout.c

https://github.com/BlueBrain/CoreNeuron/issues/670 should be fixed once the CoreNEURON submodule for mod2c includes this change.
Without this patch, the code between the two `// MARKER` comments below was not emitted.
```c++
for (_iml = 0; _iml < _cntml_actual; ++_iml) {
#ifdef _OPENACC
if (_nt->compute_gpu) {
#pragma acc atomic update
_vec_rhs[_nd_idx] += _rhs;
#pragma acc atomic update
_vec_d[_nd_idx] -= _g;
if (_nt->nrn_fast_imem) {
#pragma acc atomic update
_nt->nrn_fast_imem->nrn_sav_rhs[_nd_idx] += _rhs;
#pragma acc atomic update
_nt->nrn_fast_imem->nrn_sav_d[_nd_idx] -= _g;
}
} else {
_vec_shadow_rhs[_iml] = _rhs;
_vec_shadow_d[_iml] = _g;
}
#else
_vec_shadow_rhs[_iml] = _rhs;
_vec_shadow_d[_iml] = _g;
#endif
}
#ifdef _OPENACC
if (!(_nt->compute_gpu)) {
for (_iml = 0; _iml < …
```

Support fast_imem on CPU in GPU builds.

---

src/mod2c_core/CMakeLists.txt

The `bison_target` and `flex_target` macros seem to force `bison` and `flex` to be invoked with absolute paths, which leads to those absolute paths being present in the output source code. This causes avoidable `ccache` misses.
This PR changes the CMake logic to invoke `bison` and `flex` with relative paths, so the generated source code also only contains relative paths.
This follows the model of https://github.com/BlueBrain/nmodl/pull/723.
TODO:

Relative paths for bison/flex

---

src/mod2c_core/nocpout.c

Fixes neuronsimulator/nrn#1782

Compile error for POINTER variable in PROCEDURE.

---

src/mod2c_core/nocpout.c
test/validation/mod/NaSm.mod
test/validation/mod2c_core/cpp/NaSm.cpp

* With SOA layout, array variable is stored contigiously in
memory. For example, RANGE variable mtau[2] has values
[1 2   2 3   4 5 ... ]
* Our current index calculation was done as
```c++
#define mtau (_p + OFFSET + i)
for (int i=0; i < N; i++) {}
mtau[0] = X
mtau[1] = X
}
```
Note that even if mtau is an array, it's not being incremented by 2. The access becomes
```c++
mtau (_p + OFFSET + 0)[0]
mtau (_p + OFFSET + 0)[1]       <- this and next line is the same memory access!
mtau (_p + OFFSET + 1)[0]
mtau (_p + OFFSET + 1)[1]
```
Hence, we need to define top level macro as:
```c++
#define mtau (_p + OFFSET + i * ARRAY_LENGTH)
i.e.
#define mtau (_p + OFFSET + i * 2)
```

Fix for code generation with RANGE variables as an array

---

src/mod2c_core/parsact.c
test/validation/mod2c_core/cpp/NaSm.cpp
test/validation/mod2c_core/cpp/Nap_E.cpp

Take number 2 on #89 .
Having 
```
#pragma omp atomic update
#pragma acc atomic update
```
with OpenMP and GPU/OpenACC enabled with `mod2c` generates the following issue: 
```
NVC++-S-0155-Invalid atomic region.  (x86_64/corenrn/mod2c/axial.cpp: 346)
NVC++/x86-64 Linux 22.3-0: compilation completed with severe errors
```
For this purpose `#pragma omp atomic update` can be removed since we never have `#pragma omp simd` in `mod2c` and `#pragma ivdep` is disabled when we have either `PROTECT`, `MUTEX` or `MUTEUNLOCK`.
For the same reason I think `#pragma omp critical` can also be removed.

Remove omp atomic update and critical

---

src/mod2c_core/nocpout.c

See https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-0/use-predefined-macros-to-specify-intel-compilers.html for `icpx`.

icpx: check for __INTEL_LLVM_COMPILER
